use project_dh;

--

-- 1. Which category generates highest revenue?

select category, round(sum(purchase_amount),2) as 'total_sales' from cust_behav
group by category
order by total_sales desc;


-- 2. Are discounts actually increasing purchase value?

select category, discount_applied, 
round(sum(purchase_amount)) as 'total_sales',
round(sum(sum(purchase_amount)) over (partition by category)) as 'total_per_category',
round(sum(purchase_amount)/sum(sum(purchase_amount)) over (partition by category)*100) as 'percent_contribution',
round(sum(sum(purchase_amount)) over (partition by discount_applied)) as 'total_per_discount'
from cust_behav
group by category , discount_applied 
order by category asc, total_sales desc;


-- 3. What is the total revenue generated by male and female customer ?

select category, gender,
round(sum(sum(purchase_amount)) over ()) as'total_sales',
round(sum(sum(purchase_amount)) over (partition by gender)) as'sales_per_gender',
round(sum(sum(purchase_amount)) over( partition by category)) as 'sales_per_cat',
round(sum(sum(purchase_amount)) over (partition by category, gender)) as 'sales_per_gender_per_cat'
from cust_behav
group by category, gender
order by category asc, sales_per_gender_per_cat desc;


-- 4. Which customer used a discount but still spent more then the average purchase amount ?

select customer_id, round(purchase_amount,2), discount_applied,
(select round(avg(purchase_amount),2) from cust_behav) as 'total_avg'
from cust_behav
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from cust_behav)
order by purchase_amount desc;


-- 5. Which are the top/bottom 5 products with the highest average review rating. 

SELECT item_purchased, ROUND(AVG(review_rating),2) AS Avg_ratings
FROM cust_behav
GROUP BY item_purchased
ORDER BY Avg_ratings DESC
limit 5;
SELECT item_purchased, ROUND(AVG(review_rating),2) AS Avg_ratings
FROM cust_behav
GROUP BY item_purchased
ORDER BY Avg_ratings ASC
limit 5;


-- 6. Average purchase: Standard vs Express shipping

SELECT shipping_type,
COUNT(DISTINCT customer_id) as order_placed,
ROUND(AVG(purchase_amount),2)  as avg_purchase,
ROUND(SUM(purchase_amount),2) AS revenue
FROM cust_behav
GROUP BY shipping_type
ORDER BY revenue DESC;


-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.

SELECT category ,subscription_status,
COUNT(customer_id) as users,
ROUND(AVG(purchase_amount),2) as avg_revenue,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM cust_behav
GROUP BY subscription_status, category
ORDER BY category asc, total_revenue DESC;
 -- ----------------------------------------------- --
SELECT subscription_status,
COUNT(customer_id) as users,
ROUND(AVG(purchase_amount),2) as avg_revenue,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM cust_behav
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- 8. Top 5 products with highest discount usage %

SELECT item_purchased,
COUNT(item_purchased) AS total_number_of_times_sold,
COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) AS  Number_of_times_sold_when_disocunt_applied,
COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) *100.0 / COUNT(*) AS discount_percent
FROM cust_behav
GROUP BY item_purchased
ORDER BY discount_percent DESC
limit 5; 


-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, and show the count of each segment.

SELECT 
CASE 
	WHEN previous_purchases= '0' THEN 'New Customer'
	WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM cust_behav
GROUP BY customer_segment;


-- 10. What are the top 3 most purchased products within each category ?

WITH CTE AS (
SELECT category, item_purchased,
COUNT(item_purchased) AS most_purchased,
DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM cust_behav
GROUP BY category,item_purchased)
SELECT * FROM CTE
WHERE RNK <=3;


-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ? 

SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count,
	COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
										WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									    END) AS percents
FROM cust_behav
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status;
    
    
-- 12. What is the revenue contribution of each age group ?

SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount),2) AS total_revenue
FROM cust_behav
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC;
    

-- 13. Sales per payment method.

select payment_method, 
round(sum(purchase_amount),2) as 'sales_per_method' from cust_behav
group by payment_method;


-- 14. Sales per season.

select season, 
sum(purchase_amount) as 'sales_per_season' from cust_behav
group by season;


-- 15. Sales per size within categories.

select category, size, 
sum(purchase_amount) as 'sales_per_size',
sum(sum(purchase_amount)) over (partition by category)
from cust_behav
where category in ('Clothing','Outerwear')
group by category, size
order by category asc, sales_per_size desc;


